PMM-5257 Add socket connection to ProxySQL
percona/pmm-admin pull request #101
Opened 2020-04-29 21:42 UTC by askomorokhov

https://jira.percona.com/browse/PMM-5257

2020-04-30 11:53 UTC, BupycHuk approved these changes

2020-04-30 15:01 UTC, percona-csalguero requested changes

2020-04-30 15:01 UTC, percona-csalguero commented on commands/management/add_proxysql.go
> +	serviceName = cmd.GetServiceName()
Why do we call an exported function to get an internal variable?
The same for GetAddress() below

2020-05-01 09:20 UTC, askomorokhov commented on commands/management/add_proxysql.go
> +	serviceName = cmd.GetServiceName()
Thanks, good point. Moved common code to base file.

2020-05-01 09:32 UTC, BupycHuk commented on commands/management/add.go
> +	if socket == "" {
```suggestion
	if socket == "" && address == "" {
```

2020-05-01 11:44 UTC, BupycHuk approved these changes

2020-05-01 12:24 UTC, artemgavrilov approved these changes

2020-05-01 12:59 UTC, percona-csalguero approved these changes

2020-05-19 13:23 UTC, merged