PMM-6904 Return node name for non-generic node
percona/pmm-admin pull request #128
Opened 2020-12-15 10:34 UTC by Dasio

2020-12-15 10:51 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/pmm-admin?pullRequest=128) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pmm-admin?pullRequest=128) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pmm-admin?pullRequest=128) it.</sub>

2020-12-16 18:40 UTC, percona-csalguero approved these changes

2020-12-29 08:55 UTC, askomorokhov approved these changes

2020-12-29 09:26 UTC, BupycHuk requested changes

2020-12-29 09:26 UTC, BupycHuk commented on commands/annotation.go
> +	return "", errors.Wrap(errNoNode, "nodeName")
let's move it to `default` of `switch` and return error with message like `Unknown node type`

2020-12-29 09:56 UTC, BupycHuk commented
Please create Feature Build(FB).

2021-01-04 14:27 UTC, BupycHuk approved these changes

2021-01-14 07:19 UTC, merged