PMM-7946 Add pmm server version check and nice error to HAProxy.
percona/pmm-admin pull request #149
Opened 2021-04-23 11:58 UTC by JiriCtvrtka

2021-04-23 16:08 UTC, percona-csalguero approved these changes

2021-04-27 00:59 UTC, BupycHuk commented
we have version comparer in `pmm` repo, let's reuse it

2021-04-27 01:00 UTC, BupycHuk requested changes
we have version comparer in `pmm` repo, let's reuse it

2021-04-27 11:09 UTC, askomorokhov approved these changes
Looks good to me! 👍

2021-05-03 09:02 UTC, BupycHuk approved these changes

2021-05-03 09:02 UTC, BupycHuk commented on helpers/helpers.go
> +const HAProxyMinPMMServerVersion = "2.15.0"
```suggestion
const haProxyMinPMMServerVersion = "2.15.0"
```

2021-05-03 11:59 UTC, merged