PMM-8259 Update custom message for server error
percona/pmm-admin pull request #166
Opened 2021-10-26 09:21 UTC by ShashankSinha252

In case of 401 or 403 HTTP status response from server, pmm-admin
appends a custom message to error response from server. The message
causes mismatch between HTTP status code and updated error message.

With this change, we will provide custom message only for 401 HTTP status code. This will avoid mismatch between HTTP status code and additional error message.

2021-10-26 09:21 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/signed)](https://cla-assistant.percona.com:443/percona/pmm-admin?pullRequest=166) <br/>All committers have signed the CLA.

2021-10-26 10:50 UTC, percona-csalguero approved these changes

2021-10-27 16:20 UTC, percona-csalguero approved these changes

2021-10-28 09:23 UTC, BupycHuk requested changes

2021-10-28 09:23 UTC, BupycHuk commented on main.go
> -			}
we should keep this suffix for 401.

2021-10-28 10:00 UTC, floatinginbits commented on main.go
> -			}
Is there an advantage for retaining a check for 401 HTTP status code? We can keep a check here or ensure that error messages from source provides enough information to take corrective action.

2021-10-28 11:23 UTC, BupycHuk commented on main.go
> -			}
Yes, 401 means unauthorized, so it makes sense.

2021-10-30 04:35 UTC, ShashankSinha252 commented on main.go
> -			}
Done

2021-10-31 15:11 UTC, BupycHuk approved these changes

2021-11-05 05:00 UTC, merged