PMM-3810 Implement `pmm-admin inventory add node`.
percona/pmm-admin pull request #2
Opened 2019-04-08 15:25 UTC by BupycHuk

2019-04-08 15:26 UTC, it-percona commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/pmm-admin?pullRequest=2) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pmm-admin?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pmm-admin?pullRequest=2) it.</sub>

2019-04-09 06:50 UTC, AlekSi commented on main.go
> +	"github.com/percona/pmm-admin/commands/inventory"
Move that import below.

2019-04-09 06:50 UTC, AlekSi commented
Looking into CI failure…

2019-04-09 07:00 UTC, AlekSi requested changes
```
$ pmm-admin --help
pmm-admin: error: duplicate command "node", try --help
```

2019-04-09 07:10 UTC, AlekSi commented on commands/inventory/add_node.go
> +// Package inventory provides inventory commands.
Package-level comment should be present only in one file.

2019-04-09 07:11 UTC, AlekSi commented on commands/inventory/add_node_generic.go
> +	Node *nodes.AddGenericNodeOKBodyGeneric
Add `json` tag for `--json` output.

2019-04-10 06:51 UTC, AlekSi requested changes

2019-04-10 06:51 UTC, AlekSi commented on commands/inventory/inventory.go
> +	InventoryAddC = InventoryC.Command("add", "Add to inventory commands.")
Both should not be exported.

2019-04-10 06:51 UTC, AlekSi commented on commands/inventory/add_node_container.go
> +var addContainerNodeResultT = commands.ParseTemplate(`
`addNodeContainerResultT`

2019-04-10 06:51 UTC, AlekSi commented on commands/inventory/add_node_container.go
> +type addContainerNodeResult struct {
`addNodeContainerResult`

2019-04-10 06:51 UTC, AlekSi commented on commands/inventory/add_node_container.go
> +// register command
commands

2019-04-10 06:51 UTC, AlekSi commented on commands/inventory/add_node_generic.go
> +var addGenericNodeResultT = commands.ParseTemplate(`
addNodeGenericResultT

2019-04-10 06:51 UTC, AlekSi commented on commands/inventory/add_node_generic.go
> +// register command
commands

2019-04-10 08:43 UTC, AlekSi commented
Also it looks like commands are not registered:
```
pmm-admin add -h
usage: pmm-admin add <command> [<args> ...]

Add Service to monitoring.

Flags:
  -h, --help                   Show context-sensitive help (also try --help-long and --help-man).
      --version                Show application version.
      --server-url=SERVER-URL  PMM Server URL.
      --server-insecure-tls
      --debug                  Enable debug logging.
      --trace                  Enable trace logging (implies debug).
      --json                   Enable JSON output.

Subcommands:
  add mysql [<flags>] [<address>] [<name>]
    Add MySQL to monitoring.
```

2019-04-10 08:44 UTC, BupycHuk commented
try pmm-admin inventory add -h

2019-04-10 08:47 UTC, AlekSi commented
My bad. :) `pmm-admin -h` works.

Please also see updated ticket about custom labels.

2019-04-10 09:28 UTC, BupycHuk commented on commands/inventory/add_node_container.go
> +// register command
why commands?

2019-04-10 09:38 UTC, AlekSi commented on commands/inventory/add_node_container.go
> +// register command
My bad. :)

2019-04-10 09:39 UTC, AlekSi commented on commands/inventory/add_node_generic.go
> +// register command
wrong

2019-04-10 14:00 UTC, AlekSi requested changes
Please fix and re-check this PR yourself with attention.

2019-04-10 14:00 UTC, AlekSi commented on commands/inventory/add_node_container.go
> +	NodeType            string
Not used, remove.

2019-04-10 14:00 UTC, AlekSi commented on commands/inventory/add_node_container.go
> +	Address             string
Should be used (for now).

2019-04-10 14:00 UTC, AlekSi commented on commands/inventory/add_node_container.go
> +	customLabels, err := parseCustomLabels(cmd.CustomLabels)
`err` is ignored.

2019-04-10 14:00 UTC, AlekSi commented on commands/inventory/add_node_generic.go
> +	NodeType      string
Not used, remove.

2019-04-10 14:00 UTC, AlekSi commented on commands/inventory/add_node_container.go
> +	AddNodeContainerC.Flag("address", "Address.").StringVar(&AddNodeContainer.Address)
Custom labels are not set.

2019-04-11 10:19 UTC, AlekSi approved these changes

2019-04-11 10:19 UTC, merged