PMM-9729 update go to 1.18
percona/pmm-admin pull request #201
Opened 2022-04-18 11:20 UTC by artemgavrilov

PMM-9729

Build: SUBMODULES-0

- [ ] Links to other linked pull requests (optional).

2022-04-18 11:37 UTC, artemgavrilov commented on .github/workflows/go.yml
> -        run: make check
We invoke `ci-reviewdog` few lines above

2022-04-18 11:38 UTC, artemgavrilov commented on Makefile
> -check-all: check check-style    ## Run all linters for new code..
Left single `check` target to have it consistent with other repos

2022-04-18 13:24 UTC, BupycHuk approved these changes

2022-04-18 13:39 UTC, percona-csalguero requested changes

2022-04-18 13:39 UTC, percona-csalguero commented on Makefile
> +	$(BIN_PATH)/goimports -local github.com/percona/pmm-agent -l -w $(FILES)
This `pmm-agent` is correct?

2022-04-18 14:55 UTC, artemgavrilov commented on Makefile
> +	$(BIN_PATH)/goimports -local github.com/percona/pmm-agent -l -w $(FILES)
Nope, copy-paste error. Fixed.

2022-04-20 11:56 UTC, percona-csalguero approved these changes

2022-04-20 12:02 UTC, merged