PMM-3826 inventory remove node
percona/pmm-admin pull request #5
Opened 2019-04-11 12:43 UTC by BupycHuk

2019-04-12 06:29 UTC, idexter approved these changes

2019-04-15 10:54 UTC, AlekSi requested changes
And please resolve merge conflicts.

2019-04-15 10:54 UTC, AlekSi commented on commands/inventory/remove_node.go
> +	RemoveNodeC.Arg("node_id", "Node ID").StringVar(&RemoveNode.NodeID)
`node-id`

2019-04-16 14:20 UTC, idexter approved these changes

2019-04-18 10:43 UTC, AlekSi approved these changes

2019-04-18 10:43 UTC, merged