PMM-4011 Re-add remote monitoring.
percona/pmm-admin pull request #53
Opened 2019-08-14 15:34 UTC by BupycHuk

2019-08-15 10:58 UTC, idexter approved these changes

2019-09-03 09:20 UTC, AlekSi requested changes

2019-09-03 09:20 UTC, AlekSi commented on commands/inventory/add_node_remote.go
> +	Node *nodes.AddRemoteNodeOKBodyRemote `json:"Remote"`
All our JSON tags should be in `lower_snake_case`. Change to `"remote"` there, and check everywhere.

2019-09-03 09:20 UTC, AlekSi commented on commands/inventory/add_node_remote.go
> +	AddNodeRemoteC = addNodeC.Command("Remote", "Add Remote node to inventory")
All commands should be lower-case.

2019-09-04 10:47 UTC, closed without merging