PMM-4534 Added cli options for TLS in PostgreSQL
percona/pmm-admin pull request #56
Opened 2019-08-26 14:32 UTC by percona-csalguero

- Added tls param to enable TLS support
- Added tls-skip-verifify so set the ssl-mode.
  - true : use ssl-mode = required
  - false: use ssl-mode = verify-full

2019-08-26 14:33 UTC, it-percona commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/pmm-admin?pullRequest=56) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pmm-admin?pullRequest=56) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pmm-admin?pullRequest=56) it.</sub>

2019-08-26 14:35 UTC, BupycHuk approved these changes

2019-08-28 17:03 UTC, AlekSi requested changes
Please also add it to `pmm-admin add postgresql` Management API command.

2019-09-10 20:30 UTC, AlekSi commented on commands/inventory/add_service_postgresql.go
> +		BoolVar(&AddServicePostgreSQL.TLSSkipVerify)
There is no TLS options for service. I will remove them.

2019-09-10 20:32 UTC, AlekSi commented on commands/management/add_postgresql.go
> +		BoolVar(&AddPostgreSQL.SkipConnectionCheck)
Wrong variable. I will update.

2019-09-10 20:33 UTC, AlekSi approved these changes

2019-09-10 20:34 UTC, AlekSi commented
Will merge tomorrow morning.

2019-09-11 05:39 UTC, merged