PMM-5003 Updated status command
percona/pmm-admin pull request #95
Opened 2020-03-11 21:34 UTC by percona-csalguero

The status command was updated to show nice agent types and statuses as the list command

2020-03-11 22:51 UTC, BupycHuk approved these changes

2020-03-11 22:54 UTC, BupycHuk requested changes

2020-03-11 22:54 UTC, BupycHuk commented on commands/status.go
> +	"github.com/percona/pmm/api/inventorypb/types"
I'm sure it should be in the block above. Please, fix go imports.

2020-03-12 06:16 UTC, AlekSi approved these changes

2020-03-12 18:52 UTC, BupycHuk approved these changes

2020-03-12 19:10 UTC, merged