PMM-4145 RDS disable metrics flags.
percona/pmm-admin pull request #96
Opened 2020-03-12 07:45 UTC by askomorokhov

https://jira.percona.com/browse/PMM-4145

ref:
 - https://github.com/percona/pmm/pull/500

2020-03-12 13:54 UTC, BupycHuk approved these changes

2020-03-12 13:58 UTC, BupycHuk requested changes

2020-03-12 13:58 UTC, BupycHuk commented on commands/inventory/add_agent_rds_exporter.go
> +Disabled Basic Metrics    : {{ .Agent.DisableBasicMetrics }}
looks like it should be `.Agent.BasicMetricsDisabled` and `EnhancedMetricsDisabled` here.

2020-03-12 15:11 UTC, askomorokhov commented on commands/inventory/add_agent_rds_exporter.go
> +Node ID                   : {{ .Agent.NodeID }}
According to https://github.com/percona/pmm/pull/500/files#diff-d8f7a0a7d4635c8a9d269712db67f417R304

2020-03-12 15:22 UTC, BupycHuk approved these changes

2020-03-19 18:10 UTC, AlekSi commented on commands/inventory/add_agent_rds_exporter.go
> +	AddAgentRDSExporterC.Flag("disable-enhanced-metrics", "Disable Enhanced Metrics").BoolVar(&AddAgentRDSExporter.DisableEnhancedMetrics)
We should not capitalise "Metrics" there.

2020-03-19 18:12 UTC, AlekSi requested changes

2020-03-19 18:12 UTC, AlekSi commented on commands/inventory/add_agent_rds_exporter.go
> +Disabled Enhanced Metrics : {{ .Agent.EnhancedMetricsDisabled }}
Enhanced metrics disabled.

2020-03-20 09:08 UTC, AlekSi approved these changes

2020-03-24 09:26 UTC, AlekSi commented on Gopkg.toml
> +  branch = "PMM-4145-rds-disable-metric-collection"
Merged

2020-03-26 13:06 UTC, percona-csalguero approved these changes

2020-04-06 09:00 UTC, merged